import type { Metadata } from "next";
import { Titan_One } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

const titanOne = Titan_One({
  weight: ["400"],
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={titanOne.className}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
